name: Convert DBML to SVG

on:
  push:
    paths:
      - '**/*.dbml'

permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install DBML Renderer
        run: npm install -g @softwaretechnik/dbml-renderer

      - name: Convert DBML to SVG and Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Check for initial commit situation
          if git rev-parse HEAD >/dev/null 2>&1; then
            # Repository has at least one commit
            modified_dbml=$(git diff --name-only HEAD^ HEAD -- '*.dbml')
          else
            # This is the first commit
            modified_dbml=$(git ls-files -o --exclude-standard -- '*.dbml')
          fi
          
          echo "Modified DBML files: $modified_dbml"
          changes_made=false
          
          for file in $modified_dbml
          do
            if [ -f "$file" ]; then
              svg_file="${file%.dbml}.svg"
              dbml-renderer -i "$file" -o "$svg_file"
              git add "$svg_file"
              changes_made=true
            fi
          done
          
          if [ "$changes_made" = true ]; then
            git commit -m "Update DBML SVG Diagrams" --allow-empty
            git push
          else
            echo "No DBML files were modified or no changes needed."
