name: Convert DBML to SVG

on:
  push:
    paths:
      - '**/*.dbml'

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Specify the Node.js version

      - name: Install DBML Renderer
        run: npm install -g @softwaretechnik/dbml-renderer

      - name: Convert DBML to SVG
        run: |
          for file in $(find . -name "*.dbml"); do
            dbml-renderer -i $file -o $file.svg
          done

      - name: Commit and Push SVG Images
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update DBML SVG Diagrams" --allow-empty
          git push
