name: Convert Specific DBML to SVG

on:
  push:
    paths:
      - '**/schema.dbml' # Specify the path to the specific DBML file

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Specify the Node.js version

      - name: Install DBML Renderer
        run: npm install -g @softwaretechnik/dbml-renderer

      - name: Convert Specific DBML to SVG
        run: |
          file="./schema.dbml" # Adjust the path as needed
          svg="${file%.dbml}.svg"
          if [ -f "$file" ]; then
            if [ -f "$svg" ]; then
              chmod +w "$svg" # Ensure the file is writable
            fi
            dbml-renderer -i "$file" -o "$svg"
            echo "$svg has been updated."
          else
            echo "The specified DBML file does not exist."
          fi

      - name: Commit and Push SVG Image
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f "$svg" # Force add the SVG file
          git commit -m "Update specific DBML SVG Diagram" --allow-empty
          if git status | grep 'nothing to commit'; then
            echo "No changes to commit."
          else
            git push
          fi

